### ISSUE TITLE
recursive doesn't work

### ISSUE THREAD

**Issue by panov-andy** [MindFlavor/prometheus_folder_size_exporter#3]
Hi,
Thank you that you wrote this very useful tool but looks like recursive doesn't work or I understand it wrong.

In response, I have got only two folders which I specify but I was expecting to see all folders in my home directory.
Please, can you check what might be wrong?

```config.json
[
  { "path": "/var/log/", "recursive": false },
  { "path": "/home/andrey/", "recursive": true }
]
```

```
prometheus_folder_size_exporter -i config.json
[2020-11-28T23:30:26Z INFO  prometheus_folder_size_exporter] using options: Options { folders_file: "config.json", verbose: false, folders_to_scan: FolderScanner { folders: [FolderToScan { path: "/var/log/", recursive: false, user: None }, FolderToScan { path: "/home/andrey/", recursive: true, user: None }] } }
[2020-11-28T23:30:26Z INFO  prometheus_folder_size_exporter] starting exporter on 0.0.0.0:9974
```

```
folder_size{path="/var/log/",recursive="false"} 7160401
folder_size{path="/home/andrey/",recursive="true"} 98957688368
```

**Comment by MindFlavor** [comment]
Hi @panov-andy,
the `recursive="true"` option calculates the size of the folder *plus* all its subfolders. 

For example, if you have 

Folder | Size 
-- | --
`/home/andrey` | 10 MB
`/home/andrey/sub` | 100 MB

Specifying `{ "path": "/home/andrey/", "recursive": false }` you get `folder_size{path="/home/andrey/",recursive="false"} 10 MB`. 
Using `{ "path": "/home/andrey/", "recursive": true}` you get `folder_size{path="/home/andrey/",recursive="true"} 110 MB`.

Do you want a single line for each folder?

**Comment by MindFlavor** [comment]
I've changed the way the exporter handles subfolders. Now you can specify `Sum` to get the previous behavior but you can also specify `Explode` to get an entry for each subfolder.

Please let me know what you think!

**Comment by panov-andy** [comment]
Thank you, works as expected :) 

Just a side note about naming. Now the field `recurse_type` plays many roles. In one case, it calculates the size of subfolders in another print them and with `None` I suspect it calculates the size of files at first level only.

Might be `recursive` to indicate if it should scan subfolders.
The depth of scan (It's more like another feature request)
Explode: true, false

Please treat it as an example of naming which confuses less and not as a feature request.
