### ISSUE TITLE
limit recursive depth for Explode mode

### ISSUE THREAD

**Issue by panov-andy** [MindFlavor/prometheus_folder_size_exporter#5]
Hope I'm not asking too much :)
As an example, I want to monitor `/home/` folder itself and all subfolders there but not more. 
For that case, `depth` would be `1`.

I hope it will let me monitor `/` folder and not be that precise with settings.

**Comment by MindFlavor** [comment]
Yes, I believe it makes perfect sense!

**Comment by MindFlavor** [comment]
The PR above should solve your issue. I will merge it and make a release ASAP but please let me know if it works for you!

**Comment by panov-andy** [comment]
Hi, it works but too slow. Not sure if it's the issue for Prometheus, but I can't see the result there at the moment.

Here my measures:
```
# time curl localhost:9974/metrics
# HELP folder_size Size of the folder, including the subfolders if "explode_depth" is zero and "sum_remaining_subfolders" is true
# TYPE folder_size counter
folder_size{path="/var/jenkins_home/tools",explode_depth="0",sum_remaining_subfolders="true"} 126485398
folder_size{path="/var/jenkins_home/.ssh",explode_depth="0",sum_remaining_subfolders="true"} 2747
....

real	2m15.776s
user	0m0.008s
sys	0m0.004s
```
In total it's 400 Gb of files.

```config.json
[
  { "path": "/var/jenkins_home/", "explode_depth": 1, "sum_remaining_subfolders": true }
]
```

I suspect that response time might be the issue for Prometheus to wait that long...

**Comment by MindFlavor** [comment]
Unfortunately there is not much we can do to speed things up, a FS being what it is. I'll try to parallelize the exploration but I suspect we are IO bound, not CPU bound so it won't help us.

Another way would be to spawn a background thread that scans the files every *X* seconds and updates a buffer that will be presented to Prometheus. It will be very fast but not accurate. It will also scan the fs regardless of Prometheus polls (which kind of defeats the purpose of using a poll architecture in the first place).

**Comment by MindFlavor** [comment]
I have a PR that allows to optionally specify a background, parallel, scan. It should make the exporter faster. 
Can you please try it? 

It's here: #7.

**Comment by panov-andy** [comment]
Hi @MindFlavor ,
It's working as expected. Thank you very much :)

Best,
Andrey.
