### ISSUE TITLE
rename folder_size

### ISSUE THREAD

**Issue by panov-andy** [MindFlavor/prometheus_folder_size_exporter#8]
Hi,
Looking for metrics in other products I see metrics like `go_memstats_heap_alloc_bytes`.
Don't you think it worth renaming it to something like `folder_size_bytes` to reflect actual data size?
Also, it's often `_total` is used but I don't know any common habits \ rules about it.

Best,
Andrey.

**Comment by MindFlavor** [comment]
Yes `folder_size_bytes` is better. Changing it now.
